"au BufNewFile,BufRead *.shader setf c
"au BufNewFile,BufRead *.jade setf sass
"au BufNewFile,BufRead *.soy setf html
"au BufNewFile,BufRead *.styl setf sass
au BufNewFile,BufRead *.json setf javascript
au BufNewFile,BufRead *.jsx setf javascript
au BufNewFile,BufRead *.es6 setf javascript
au BufNewFile,BufRead *.css set filetype=scss.css
au BufNewFile,BufRead *.slim set filetype=pug
